/**
 * Structural subset of the OpenClaw 2026.7.1 public plugin contracts used by
 * Simai. Keeping the import surface structural makes this package buildable
 * without bundling OpenClaw, while the names/signatures mirror the official
 * `types`, `hook-message.types`, and `tool-types` contracts from v2026.7.1.
 */

export type PluginRegistrationMode =
  | "full"
  | "discovery"
  | "tool-discovery"
  | "setup-only"
  | "setup-runtime"
  | "cli-metadata";

export interface PluginHookMessageReceivedEvent {
  from: string;
  content: string;
  timestamp?: number;
  threadId?: string | number;
  messageId?: string;
  senderId?: string;
  sessionKey?: string;
  runId?: string;
  metadata?: Record<string, unknown>;
}

export interface PluginHookMessageContext {
  channelId: string;
  accountId?: string;
  conversationId?: string;
  sessionKey?: string;
  runId?: string;
  messageId?: string;
  senderId?: string;
}

/** `message:preprocessed` is an internal hook, not a typed lifecycle hook. */
export interface MessagePreprocessedHookEvent {
  type: "message";
  action: "preprocessed";
  sessionKey?: string;
  timestamp?: number;
  messages: string[];
  context: {
    bodyForAgent?: string;
    from?: string;
    channelId: string;
    conversationId?: string;
    messageId?: string;
    senderId?: string;
    isGroup?: boolean;
  };
}

export interface DeliveryContext {
  channel?: string;
  accountId?: string;
  to?: string;
  threadId?: string | number;
}

/** Trusted context captured by an OpenClaw plugin tool factory. */
export interface OpenClawPluginToolContext {
  agentId?: string;
  sessionKey?: string;
  sessionId?: string;
  messageChannel?: string;
  agentAccountId?: string;
  deliveryContext?: DeliveryContext;
  requesterSenderId?: string;
  senderIsOwner?: boolean;
}

export interface AgentToolResult {
  content: Array<{ type: "text"; text: string }>;
  details?: unknown;
}

export interface AgentTool {
  name: string;
  label: string;
  description: string;
  parameters: Record<string, unknown>;
  execute(
    toolCallId: string,
    params: unknown,
    signal?: AbortSignal,
    onUpdate?: unknown,
  ): Promise<AgentToolResult>;
}

export type OpenClawPluginToolFactory = (
  ctx: OpenClawPluginToolContext,
) => AgentTool | AgentTool[] | null | undefined;

export interface OpenClawPluginApi {
  id: string;
  registrationMode: PluginRegistrationMode;
  pluginConfig?: Record<string, unknown>;
  logger: {
    info(message: string): void;
    warn(message: string): void;
    error(message: string): void;
  };
  resolvePath(input: string): string;
  on(
    event: "message_received",
    handler: (
      event: PluginHookMessageReceivedEvent,
      ctx: PluginHookMessageContext,
    ) => void | Promise<void>,
    opts?: { priority?: number; timeoutMs?: number },
  ): void;
  registerHook(
    events: string | string[],
    handler: (event: MessagePreprocessedHookEvent) => void | Promise<void>,
    opts?: { name?: string; description?: string; register?: boolean },
  ): void;
  registerTool(
    tool: OpenClawPluginToolFactory,
    opts?: { name?: string; names?: string[]; optional?: boolean },
  ): void;
}

export interface OpenClawPluginDefinition {
  id: string;
  name: string;
  description: string;
  version?: string;
  register(api: OpenClawPluginApi): void;
}

export interface SimaiPluginConfig {
  /** Loopback core-service URL, for example http://127.0.0.1:18880. */
  coreUrl: string;
  /** Owner-only token file generated by the Simai service. */
  coreTokenFile: string;
  /** Sealed inbox Unix socket path. */
  inboxSocket: string;
  /** Public vault header used for encrypted direct-write fallback. */
  vaultHeaderPath: string;
  /** Ciphertext-only inbox directory used for atomic fallback writes. */
  inboxDir: string;
  /** Maximum lifetime of a two-phase correlation and tool authorization. */
  correlationWindowMs?: number;
  bindings: SimaiBinding[];
}

export interface SimaiBinding {
  id: string;
  channel: string;
  accountId: string;
  senderKey: string;
  conversationId?: string;
  allowGroup: boolean;
  passiveCapture: boolean;
  enabled: boolean;
}

export type CaptureMode = "passive" | "explicit";

export interface VerifiedIdentity {
  bindingId: string;
  channel: string;
  accountId: string;
  senderKey: string;
  conversationId: string | null;
  isGroup: boolean;
  messageId: string;
  sessionKey: string | null;
  captureMode: CaptureMode;
  receivedAt: number;
}
